# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GpOLkwdRJ_0_TuOIBoNFTQrMFMFrVS8S
"""

import os
from os.path import exists
def importDataSet():
  cwd = os.getcwd()
  train_dir='inaturalist_12K/train/' 
  test_dir='inaturalist_12K/val/'
  savePath=cwd+'/DataSet/'
  classes=['Amphibia','Animalia','Arachnida','Aves','Fungi','Insecta','Mammalia','Mollusca','Plantae','Reptilia']
  file_exists = exists(cwd+'/DataSet/nature_12K.zip')
  if(file_exists==False):
    os.system('curl -SL https://storage.googleapis.com/wandb_datasets/nature_12K.zip > nature_12K.zip')
  extract_exists = exists(cwd+'/inaturalist_12K/')   
  if(extract_exists==False):  
    os.system('unzip nature_12K.zip')